spring:
  application:
    name: core
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/note
    username: admin
    password: password
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 7781
cloud:
  accessKey:
  secretKey:
  link-lifetime: 15
  bucket-name: test-mail
  service-endpoint: https://storage.yandexcloud.net
  signing-region: ru-central1
images:
  permitted-format: .jpg, .png, .gif