spring:
  application:
    name: core
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/note
    username: admin
    password: password
  rabbitmq:
    host: localhost
    port: 5672

